/*DROP REFERENCES*/
ALTER TABLE SYSTEM.ALUNO
DROP CONSTRAINT ALUNO_INSTRUTOR_MATRICULA_FK;

ALTER TABLE SYSTEM.PAGAMENTO
DROP CONSTRAINT PAGAMENTO_ALUNO_MATRICULA_FK;

/*DROP INDEXES*/


/*DROP TABLES*/
DROP TABLE SYSTEM.ALUNO;
DROP TABLE SYSTEM.INSTRUTOR;
DROP TABLE SYSTEM.PAGAMENTO;

/*DROP VIEWS*/

/*DROP SEQUENCES*/
DROP SEQUENCE SYSTEM.ALUNO_MATRICULA_SEQ;
DROP SEQUENCE SYSTEM.INSTRUTOR_MATRICULA_SEQ;
DROP SEQUENCE SYSTEM.PAGAMENTO_ID_SEQ;


/*CREATE TABLES*/
CREATE TABLE SYSTEM.ALUNO ( 
    MATRICULA VARCHAR2(5) NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    CPF VARCHAR2(11) NOT NULL,
    EMAIL VARCHAR2(200) NOT NULL,
    TELEFONE VARCHAR2(11),
    DATA_NASCIMENTO DATE NOT NULL,
    INSTRUTOR VARCHAR2(100),
    /*0 para falso e 1 para verdadeiro
    coluna para saber se o aluno está matriculado*/
    CONDICAO_MATRICULA NUMBER(1) CHECK (CONDICAO_MATRICULA IN (0, 1)),
    CONSTRAINT MATRICULA_PK PRIMARY KEY (MATRICULA)
);

CREATE TABLE SYSTEM.INSTRUTOR (
    MATRICULA VARCHAR2(5) NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    CPF VARCHAR2(11) NOT NULL,
    EMAIL VARCHAR2(200) NOT NULL,
    TELEFONE VARCHAR2(11),
    ALUNOS VARCHAR2(100),
    CONSTRAINT MATRICULA_INSTRUTOR_PK PRIMARY KEY (MATRICULA)
);

CREATE TABLE SYSTEM.PAGAMENTO (
    ID VARCHAR2(5) NOT NULL,
    MATRICULA VARCHAR2(5) NOT NULL,
    DATA_PAGAMENTO DATE NOT NULL,
    CONSTRAINT ID_PAGAMENTO_PK PRIMARY KEY (ID)
);

/*CREATE SEQUENCES*/
CREATE SEQUENCE SYSTEM.ALUNO_MATRICULA_SEQ
START WITH 10000
INCREMENT BY 1
NOMAXVALUE
NOCYCLE;

CREATE SEQUENCE SYSTEM.INSTRUTOR_MATRICULA_SEQ
START WITH 77777
INCREMENT BY 1
NOMAXVALUE
NOCYCLE;

CREATE SEQUENCE SYSTEM.PAGAMENTO_ID_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE;

/*CREATE INDEXES*/


/*CREATE VIEWS*/


/*ADD FOREIGN KEY*/
/*RELAÇÃO DE PAGAMENTO DA MATRICULA*/
ALTER TABLE SYSTEM.PAGAMENTO 
ADD CONSTRAINT PAGAMENTO_ALUNO_MATRICULA_FK
FOREIGN KEY (MATRICULA)
REFERENCES SYSTEM.ALUNO (MATRICULA);

/*INSTRUTOR DO ALUNO REFERENCIADO PELA MATRICULA*/
ALTER TABLE SYSTEM.ALUNO
ADD CONSTRAINT ALUNO_INSTRUTOR_MATRICULA_FK
FOREIGN KEY (INSTRUTOR)
REFERENCES SYSTEM.INSTRUTOR (MATRICULA);

/*ALUNOS DO INSTRUTOR REFERENCIADOS PELA MATRICULA*/
ALTER TABLE SYSTEM.INSTRUTOR
ADD CONSTRAINT INSTRUTOR_ALUNO_MATRICULA_FK
FOREIGN KEY (ALUNOS)
REFERENCES SYSTEM.ALUNO (MATRICULA);


ALTER SESSION SET NLS_DATE_FORMAT = 'YYY/MM/DD';


INSERT INTO SYSTEM.INSTRUTOR (MATRICULA, NOME, CPF, EMAIL, TELEFONE)
VALUES (SYSTEM.INSTRUTOR_MATRICULA_SEQ.NEXTVAL, 'Julio Balestrin', '12345678901', 'balesgreen@mail.com', '11999999999');

INSERT INTO SYSTEM.INSTRUTOR (MATRICULA, NOME, CPF, EMAIL, TELEFONE)
VALUES (SYSTEM.INSTRUTOR_MATRICULA_SEQ.NEXTVAL, 'Renato Cariani', '12345678901', 'cariani@mail.com', '11999999999');

INSERT INTO SYSTEM.ALUNO (MATRICULA, NOME, CPF, EMAIL, TELEFONE, DATA_NASCIMENTO, INSTRUTOR, CONDICAO_MATRICULA)
VALUES (SYSTEM.ALUNO_MATRICULA_SEQ.NEXTVAL, 'Serjao Foguetes', '12345678901', 'spacetoday@mail.com', '11999999999', TO_DATE('2000-01-01', 'YYYY/MM/DD'), '77777', 1);

INSERT INTO SYSTEM.ALUNO (MATRICULA, NOME, CPF, EMAIL, TELEFONE, DATA_NASCIMENTO, INSTRUTOR, CONDICAO_MATRICULA)
VALUES (SYSTEM.ALUNO_MATRICULA_SEQ.NEXTVAL, 'Baptista Angolano', '7573773737', 'angola@mail.com', '11888888888', TO_DATE('2000-01-01', 'YYYY/MM/DD'), '77778', 1);

INSERT INTO SYSTEM.ALUNO (MATRICULA, NOME, CPF, EMAIL, TELEFONE, DATA_NASCIMENTO, INSTRUTOR, CONDICAO_MATRICULA)
VALUES (SYSTEM.ALUNO_MATRICULA_SEQ.NEXTVAL, 'Danilo Gentili', '7573773737', 'thenoite@mail.com', '11888888888', TO_DATE('2000-01-01', 'YYYY/MM/DD'), '77778', 1);

INSERT INTO SYSTEM.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (SYSTEM.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2020-01-01', 'YYYY/MM/DD'));

INSERT INTO SYSTEM.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (SYSTEM.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2020-02-01', 'YYYY/MM/DD'));

INSERT INTO SYSTEM.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (SYSTEM.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2020-03-01', 'YYYY/MM/DD'));

INSERT INTO SYSTEM.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (SYSTEM.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2020-04-01', 'YYYY/MM/DD'));

INSERT INTO SYSTEM.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (SYSTEM.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2020-05-01', 'YYYY/MM/DD'));

INSERT INTO SYSTEM.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (SYSTEM.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2020-06-01', 'YYYY/MM/DD'));

INSERT INTO SYSTEM.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (SYSTEM.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2020-07-01', 'YYYY/MM/DD'));

INSERT INTO SYSTEM.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (SYSTEM.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2020-08-01', 'YYYY/MM/DD'));

INSERT INTO SYSTEM.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (SYSTEM.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2020-09-01', 'YYYY/MM/DD'));

INSERT INTO SYSTEM.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (SYSTEM.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2020-10-01', 'YYYY/MM/DD'));

INSERT INTO SYSTEM.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (SYSTEM.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2020-11-01', 'YYYY/MM/DD'));

INSERT INTO SYSTEM.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (SYSTEM.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2020-12-01', 'YYYY/MM/DD'));

INSERT INTO SYSTEM.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (SYSTEM.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2021-01-01', 'YYYY/MM/DD'));

INSERT INTO SYSTEM.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (SYSTEM.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2021-02-01', 'YYYY/MM/DD'));

INSERT INTO SYSTEM.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (SYSTEM.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2021-03-01', 'YYYY/MM/DD'));

INSERT INTO SYSTEM.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (SYSTEM.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2021-04-01', 'YYYY/MM/DD'));

INSERT INTO SYSTEM.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (SYSTEM.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2021-05-01', 'YYYY/MM/DD'));

INSERT INTO SYSTEM.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (SYSTEM.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2021-06-01', 'YYYY/MM/DD'));

INSERT INTO SYSTEM.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (SYSTEM.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2021-07-01', 'YYYY/MM/DD'));

INSERT INTO SYSTEM.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (SYSTEM.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2021-08-01', 'YYYY/MM/DD'));

INSERT INTO SYSTEM.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (SYSTEM.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2021-09-01', 'YYYY/MM/DD'));

INSERT INTO SYSTEM.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (SYSTEM.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2021-10-01', 'YYYY/MM/DD'));

INSERT INTO SYSTEM.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (SYSTEM.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2021-11-01', 'YYYY/MM/DD'));

INSERT INTO SYSTEM.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (SYSTEM.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2021-12-01', 'YYYY/MM/DD'));