CREATE USER C##LABDATABASE IDENTIFIED BY password123;
GRANT CREATE SESSION TO C##LABDATABASE;

/*DROP REFERENCES*/
ALTER TABLE C##LABDATABASE.ALUNO
DROP CONSTRAINT ALUNO_INSTRUTOR_MATRICULA_FK;

ALTER TABLE C##LABDATABASE.PAGAMENTO
DROP CONSTRAINT PAGAMENTO_ALUNO_MATRICULA_FK;

/*DROP INDEXES*/


/*DROP TABLES*/
DROP TABLE C##LABDATABASE.ALUNO;
DROP TABLE C##LABDATABASE.INSTRUTOR;
DROP TABLE C##LABDATABASE.PAGAMENTO;

/*DROP VIEWS*/

/*DROP SEQUENCES*/
DROP SEQUENCE C##LABDATABASE.ALUNO_MATRICULA_SEQ;
DROP SEQUENCE C##LABDATABASE.INSTRUTOR_MATRICULA_SEQ;
DROP SEQUENCE C##LABDATABASE.PAGAMENTO_ID_SEQ;