
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY/MM/DD';


TRUNCATE TABLE C##LABDATABASE.ALUNO;

TRUNCATE TABLE C##LABDATABASE.INSTRUTOR;

TRUNCATE TABLE C##LABDATABASE.PAGAMENTO;


INSERT INTO C##LABDATABASE.INSTRUTOR (MATRICULA, NOME, CPF, EMAIL, TELEFONE)
VALUES (C##LABDATABASE.INSTRUTOR_MATRICULA_SEQ.NEXTVAL, 'Julio Balestrin', '12345678901', 'balesgreen@mail.com', '11999999999');

INSERT INTO C##LABDATABASE.INSTRUTOR (MATRICULA, NOME, CPF, EMAIL, TELEFONE)
VALUES (C##LABDATABASE.INSTRUTOR_MATRICULA_SEQ.NEXTVAL, 'Renato Cariani', '12345678901', 'cariani@mail.com', '11999999999');

INSERT INTO C##LABDATABASE.ALUNO (MATRICULA, NOME, CPF, EMAIL, TELEFONE, DATA_NASCIMENTO, INSTRUTOR, CONDICAO_MATRICULA)
VALUES (C##LABDATABASE.ALUNO_MATRICULA_SEQ.NEXTVAL, 'Serjao Foguetes', '12345678901', 'spacetoday@mail.com', '11999999999', TO_DATE('2000-01-01', 'YYYY/MM/DD'), '77777', 1);

INSERT INTO C##LABDATABASE.ALUNO (MATRICULA, NOME, CPF, EMAIL, TELEFONE, DATA_NASCIMENTO, INSTRUTOR, CONDICAO_MATRICULA)
VALUES (C##LABDATABASE.ALUNO_MATRICULA_SEQ.NEXTVAL, 'Baptista Angolano', '7573773737', 'angola@mail.com', '11888888888', TO_DATE('2000-01-01', 'YYYY/MM/DD'), '77778', 1);

INSERT INTO C##LABDATABASE.ALUNO (MATRICULA, NOME, CPF, EMAIL, TELEFONE, DATA_NASCIMENTO, INSTRUTOR, CONDICAO_MATRICULA)
VALUES (C##LABDATABASE.ALUNO_MATRICULA_SEQ.NEXTVAL, 'Danilo Gentili', '7573773737', 'thenoite@mail.com', '11888888888', TO_DATE('2000-01-01', 'YYYY/MM/DD'), '77778', 1);

INSERT INTO C##LABDATABASE.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (C##LABDATABASE.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2020-01-01', 'YYYY/MM/DD'));

INSERT INTO C##LABDATABASE.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (C##LABDATABASE.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2020-02-01', 'YYYY/MM/DD'));

INSERT INTO C##LABDATABASE.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (C##LABDATABASE.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2020-03-01', 'YYYY/MM/DD'));

INSERT INTO C##LABDATABASE.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (C##LABDATABASE.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2020-04-01', 'YYYY/MM/DD'));

INSERT INTO C##LABDATABASE.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (C##LABDATABASE.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2020-05-01', 'YYYY/MM/DD'));

INSERT INTO C##LABDATABASE.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (C##LABDATABASE.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2020-06-01', 'YYYY/MM/DD'));

INSERT INTO C##LABDATABASE.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (C##LABDATABASE.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2020-07-01', 'YYYY/MM/DD'));

INSERT INTO C##LABDATABASE.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (C##LABDATABASE.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2020-08-01', 'YYYY/MM/DD'));

INSERT INTO C##LABDATABASE.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (C##LABDATABASE.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2020-09-01', 'YYYY/MM/DD'));

INSERT INTO C##LABDATABASE.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (C##LABDATABASE.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2020-10-01', 'YYYY/MM/DD'));

INSERT INTO C##LABDATABASE.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (C##LABDATABASE.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2020-11-01', 'YYYY/MM/DD'));

INSERT INTO C##LABDATABASE.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (C##LABDATABASE.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2020-12-01', 'YYYY/MM/DD'));

INSERT INTO C##LABDATABASE.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (C##LABDATABASE.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2021-01-01', 'YYYY/MM/DD'));

INSERT INTO C##LABDATABASE.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (C##LABDATABASE.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2021-02-01', 'YYYY/MM/DD'));

INSERT INTO C##LABDATABASE.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (C##LABDATABASE.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2021-03-01', 'YYYY/MM/DD'));

INSERT INTO C##LABDATABASE.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (C##LABDATABASE.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2021-04-01', 'YYYY/MM/DD'));

INSERT INTO C##LABDATABASE.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (C##LABDATABASE.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2021-05-01', 'YYYY/MM/DD'));

INSERT INTO C##LABDATABASE.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (C##LABDATABASE.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2021-06-01', 'YYYY/MM/DD'));

INSERT INTO C##LABDATABASE.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (C##LABDATABASE.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2021-07-01', 'YYYY/MM/DD'));

INSERT INTO C##LABDATABASE.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (C##LABDATABASE.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2021-08-01', 'YYYY/MM/DD'));

INSERT INTO C##LABDATABASE.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (C##LABDATABASE.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2021-09-01', 'YYYY/MM/DD'));

INSERT INTO C##LABDATABASE.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (C##LABDATABASE.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2021-10-01', 'YYYY/MM/DD'));

INSERT INTO C##LABDATABASE.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (C##LABDATABASE.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2021-11-01', 'YYYY/MM/DD'));

INSERT INTO C##LABDATABASE.PAGAMENTO (ID, MATRICULA, DATA_PAGAMENTO)
VALUES (C##LABDATABASE.PAGAMENTO_ID_SEQ.NEXTVAL, '10000', TO_DATE('2021-12-01', 'YYYY/MM/DD'));

COMMIT;